### ISSUE TITLE
Crash on run

### ISSUE THREAD

**Issue by jumper-cable-morty** [natestutte/fnf-randomizer#2]
On Linux. Running the py file says that the assets directory doesn't exist, made sure that it was in the root directory.
Here's what the console gives me:
![image](https://user-images.githubusercontent.com/63005760/110733235-374ca680-81eb-11eb-9f67-cb1a0d93dd44.png)
And then here's the fnf directory: 
![image](https://user-images.githubusercontent.com/63005760/110733293-492e4980-81eb-11eb-8e1c-b321c68329f7.png)

**Comment by natestutte** [comment]
> On Linux. Running the py file says that the assets directory doesn't exist, made sure that it was in the root directory.
> Here's what the console gives me:
> ![image](https://user-images.githubusercontent.com/63005760/110733235-374ca680-81eb-11eb-9f67-cb1a0d93dd44.png)
> And then here's the fnf directory:
> ![image](https://user-images.githubusercontent.com/63005760/110733293-492e4980-81eb-11eb-8e1c-b321c68329f7.png)

Hi! Can you show me the contents of your assets directory if you don't mind? @jumper-cable-morty

**Comment by jumper-cable-morty** [comment]
Sure, here you go. 
![image](https://user-images.githubusercontent.com/63005760/111171155-a7a05280-8572-11eb-9d15-ab125842a3ce.png)

**Comment by natestutte** [comment]
Thank you, it seems like you're trying to run the program in the official Friday Night Funkin' repository. The program should be run in the game directory downloaded from the official itchio site: https://ninja-muffin24.itch.io/funkin

The directory should contain a "Funkin" executable and a "data" directory within "assets". I recommend you create a separate directory for using the randomizer. If you have anymore problems feel free to email me at natestutte@protonmail.com
