### ISSUE TITLE
Not compatible with song titles containing a space

### ISSUE THREAD

**Issue by RedstoneRuler** [natestutte/fnf-randomizer#5]
If a song's JSON contains a space in the "song" section (for example, Yap Squad from Bob and Bosip) it will remove it, meaning it refers to a song that does not exist. This can be manually fixed by just adding the spaces back, but it's not very convenient. 
![before](https://user-images.githubusercontent.com/87531116/149670127-1f769f4c-7e4a-48a5-ad05-563b067cad2a.PNG)
![after](https://user-images.githubusercontent.com/87531116/149670132-6540623b-d991-42f3-a669-5f25ab3f26de.PNG)

**Comment by natestutte** [comment]
This issue has been solved as of release v1.4.1

Thank you for your contribution!
